my_todo_app/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.views import static

from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_todolist.urls')),

]

my_todolist/urls.py
from django.contrib import admin
from django.urls import path,include
from my_todolist import views

app_name = 'my_todolist'
urlpatterns = [
    
    path('', views.mytask, name='mytask'),
    path("delete/<int:pk>/", views.delete_task, name='delete_task'),
    path("edit/<int:pk>/", views.edit_task, name='edit_task'),
    path("update/<int:pk>/", views.update_task, name='update_task'),
    path("edit_status/<int:pk>/<str:status>", views.edit_status, name='edit_status'),
]

my_todolist/models.py
from django.db import models
from django.utils import timezone
import datetime
# Create your models here.
class Task(models.Model):
    s = ((1,"completed"),(2,"pending"))
    taskTitle = models.CharField(max_length=30)
    taskDesc = models.CharField(max_length=200)
    added_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=250,null=True,default="pending", choices=s)


    #def was_published_recently(self):
    #   return self.time >= timezone.now() - datetime.timedelta(days=1)
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.time <= now

    def __str__(self):
        return self.taskTitle
    

my_todolist/views.py
from django.shortcuts import redirect, render
from my_todolist.models import Task
from django.utils import timezone

# Create your views here.


def mytask(request):
    thank = False
    if request.method=="POST":
        title = request.POST.get("title","")
        
        current_date=timezone.localtime(timezone.now())
 

        data = Task(taskTitle =title,added_date=current_date)
        data.save()
        thank = True
        
    todo_items= Task.objects.all().order_by("added_date")
    context =  {"todo_items":todo_items}
    #todo_items stores all the items given by Todo.objects.all()
    #i.e all the items in database in order by added_date
    return render(request,'mytask.html',context)



def edit_task(request,pk):
    task = Task.objects.get(id=pk)
    context = {'title':task.taskTitle,'id':task.id}
    return render(request, "edit_task.html",context)
def update_task(request, pk):
    task = Task(id=pk)
    if request.method=="POST":
        task.taskTitle = request.POST.get("title","")
        task.added_date=timezone.localtime(timezone.now())
        
        task.save()
        context =  {"todo_items":Task.objects.all()}
        return render(request, "mytask.html",context)
    return render(request, "edit_task.html")
def delete_task(request, pk):
    if pk:
        task = Task.objects.get(id=pk)
        task.delete()
        context =  {"todo_items":Task.objects.all()}
        return redirect("/")

    return render(request,'mytask.html')
def edit_status(request, pk,status):
    if pk:
        task = Task.objects.get(id=pk)
        task.status = status
        task.save()
        context =  {"todo_items":Task.objects.all()}
        return render(request, 'mytask.html',context)
    return render(request,'mytask.html')

my_todolist/templates/edit_task.html
<!DOCTYPE html>
<html>
<head>
    <title>To_Do</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
        <script>

        document.addEventListener('DOMContentLoaded', function(){

            //so that user don't entre empty input we can disable the submit button initially till user don't provide task.
            document.querySelector('#submit').disabled =  true;

            // now to enable submit button when user press key by using onkeyup so user can submit it input
            document.querySelector('#task').onkeyup = () =>{
                if(document.querySelector('#task').value.length >0){
                    document.querySelector('#submit').disabled =  false;
                }
                else{
                    document.querySelector('#submit').disabled =  true;
                }
                
            } 

              document.querySelector('form').onsubmit = () => {
                  const task = document.querySelector('#task').value;
                  //console.log(task);   // it will print entred task to concole window of javascript
                  const li = document.createElement('li');
                  li.innerHTML =task;
                  document.querySelector('#tasks').append(li);
                  
                  document.querySelector('#task').value = '';

                  document.querySelector('#submit').disabled =  true; //disable again after submitting input

                  //stop form from submitting so tht entred value can be shown in colsole
                  return false   // it will stop form from submitting 
              }
                    
        });

        </script>
</head>

<body >
    <nav class="navbar navbar-light " style="background-color: #e3f2fd;">
        <a class="navbar-brand " href="#">To Do App</a>
    </nav>  

<div class="row ">
    <div class="col" style="margin-left: 10px;">
        <h2>Add Item</h2>
        <form action="/update/{{id}}/" method='POST' class="row row-cols-lg-auto g-3 align-items-center">
            {% csrf_token %}
            <div class="col-12">
                <input type="text" name="title" id="task" class="form-control mb-2 mr-sm-2"  placeholder="Title" value="{{title}}">
            </div>
            
            <div class="col-12">
                <input type="text" name="complete" id="complete" class="form-control mb-2 mr-sm-2"  placeholder="Do work on">
            </div>
            
            <div class="col-12">
                <button type="submit" id="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
        <a href="{% url 'my_todolist:mytask' %}" >Check your task</a>
    </div>
</div>   
      
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    
  </body>
</html>

my_todolist/templates/mytask.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Chela+One&display=swap" rel="stylesheet">
    <title>Tasks todos</title>
  <style>
   body{
     background-color: #b6e1fe;
   }
    .mytask{
      float: right;
      
    }
    .navbar{
      height: 50px;
    }
    .mytable {
    border-collapse: collapse;
    width: 500px;
    margin-top: -300px;
    margin-right: 40px;
    font-family: sans-serif;
  
    box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
}
.mytable thead tr {
    background-color: #009879;
    color: #ffffff;
    text-align: left;
}
.mytable th,
.mytable td {
    padding: 12px 15px;
}
.mytable tbody tr {
    border-bottom: 1px solid #89cfe0;
    background-color: rgba(142, 205, 241, 0.452);
    font-size: 20px;
      
}

.mytable tbody tr:nth-of-type(even) {
    background-color: #f3f3f3;
    font-size: 20px;
}

.mytable tbody tr:last-of-type {
    border-bottom: 2px solid #009879;
}
.mytable tbody tr.active-row {
    font-weight: bold;
    color: #009879;
}
.taskform{
  margin-left: 40px;
 
}
.taskform label{
    font-size: 20px;
  }
.taskform input{
  margin-bottom: 40px;
  margin-left: 30px;
  height: 40px;
  border-radius: 0.1cm;
}
.submit{
  width: 75px;
}
.submit:hover{
  background-color: black;
}
h2{
  margin: 130px 0 40px 40px;
  color: #1e3a68;
  font-size: 40px;
  font-weight: 100;
  font-family: 'Permanent Marker', cursive;

}
.navbar-brand{
  font-size: 40px;
  margin: -15px 0 0 20px;
  font-family: 'Chela One', cursive;
}
  </style>
  <script>

    document.addEventListener('DOMContentLoaded', function(){

        //so that user don't entre empty input we can disable the submit button initially till user don't provide task.
        document.querySelector('#submit').disabled =  true;

        // now to enable submit button when user press key by using onkeyup so user can submit it input
        document.querySelector('#task').onkeyup = () =>{
            if(document.querySelector('#task').value.length >0){
                document.querySelector('#submit').disabled =  false;
            }
            else{
                document.querySelector('#submit').disabled =  true;
            }
            
        } 

          document.querySelector('form').onsubmit = () => {
              const task = document.querySelector('#task').value;
              //console.log(task);   // it will print entred task to concole window of javascript
              const li = document.createElement('li');
              li.innerHTML =task;
              document.querySelector('#tasks').append(li);
              
              document.querySelector('#task').value = '';

              document.querySelector('#submit').disabled =  true; //disable again after submitting input

              //stop form from submitting so tht entred value can be shown in colsole
              return false   // it will stop form from submitting 
          }
                
    });

    </script>
</head>

<body>
  <nav class="navbar navbar-light " style="background-color: #4aa4e1;">
    <a class="navbar-brand " href="/">To Do App</a>
  </nav>
      <h2>Add Items</h2>
      <form action="" method='POST' class="taskform" >
        {% csrf_token %}
        <div class="title"></div>
        <label>Your Task:</label>
          <input style="margin-left: 60px;" type="text" name="title" id="task"  placeholder="Title">
        </div>

        <div class="submit">
          <button type="submit" id="submit" class="btn btn-primary">Submit</button>
        </div>
      </form>
    </div>
  </div>
  <section class="mytask">
        <table class="mytable"  >
          <tbody>
            <tr  >
              <th>Username</th>

              <th>Dated On</th>
              <th>Status</th>
              <th>Delete task</th>
              <th>Update task</th>
              <th>Change status</th>

            </tr>
            {% for item in todo_items %}

            <tr >
              <td>{{item}} </td>
              <td>{{item.added_date}} </td>
              <td>{{item.status}} </td>
              <td><a style="padding-left: 45px;" href="{% url 'my_todolist:delete_task' item.id %}">🗑️</a></td>
              <td><a href="{% url 'my_todolist:edit_task' item.id %}">Update</a></td>
              <td>

                <a href="/edit_status/{{item.id}}/completed" title="completed">✅</a>

                <a href="/edit_status/{{item.id}}/pending" title="pending">🕑</a>

              </td>

            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </section>
  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
    crossorigin="anonymous"></script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->

  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"
    integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"
    integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG"
    crossorigin="anonymous"></script>

</body>

</html>